[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "python39Packages.setuptools", "chromium", "chromedriver"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python3 app.py"
