[phases.setup]
nixPkgs = ["python39", "python39Packages.pip", "chromium", "chromedriver"]

[phases.install]
cmds = ["python -m pip install -r requirements.txt"]

[phases.build]
cmds = ["echo 'Build complete'"]

[start]
cmd = "python app.py"
